#### 1. Import the numpy package under the name `np`

#### Import արեք numpy module-ը np անունով:

In [5]:
import numpy as np
np.__version__


'1.16.5'

#### 2. Create a numpy array of size 10 filled with zeros. 

#### Ստեղծեք 10 չափի 0-ներով լցված numpy array:

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3.  How to get the documentation of the numpy add function? 

#### Նայեք numpy-ի add ֆունկցիայի դոկումենտացիան:

In [7]:
help(np)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



#### 4.  Create a numpy array of size 10 filled with zeros but the fifth value is 1 

#### Ստեղծեք 10 չափի 0-ներով լցված numpy array, որի 5րդ արժեքը 1 է:

In [9]:
a=np.zeros(10)
a[4]=1
print(a)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 5.  Create a numpy array with values ranging from 10 to 49

#### Ստեղծեք 10-ից 49 հաջորդական թվերով numpy array:

In [11]:
a=np.arange(10,49)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 6.  Reverse the numpy array ranging from 0 to 50. 

#### Ստեղծեք 0-ից 50 հաջորդական թվերով numpy array և տպեք այն շրջած ձևով:

In [22]:
a=np.arange(50)
print("old a: ",a)
a=a.reshape(50,-1)
print("new a: ",a)

old a:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
new a:  [[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]
 [31]
 [32]
 [33]
 [34]
 [35]
 [36]
 [37]
 [38]
 [39]
 [40]
 [41]
 [42]
 [43]
 [44]
 [45]
 [46]
 [47]
 [48]
 [49]]


#### 7.  Create a 3x3 matrix with values ranging from 0 to 8 

#### Ստեղծեք 0-ից 8 հաջորդական թվերով 3x3 numpy array

In [29]:
a=np.arange(9).reshape(3,3)
a


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 8. Find indices of non-zero elements from \[1,2,0,0,4,0\]

#### Տրված է \[1,2,0,0,4,0\] numpy array-ը, գտեք ոչ-զրոյական արժեքներով տարրերի կոորդինատները:

In [37]:
a=np.array([1,2,0,0,4,0])
for i in range(6):
    if a[i]!=0:
        print(i)
    


0
1
4


#### 9. Create a 3x3x3 array with random integers from 1 to 20

#### Ստեղծեք 1-ից 20 պատահական թվերով լցված (3x3x3) չափանի numpy array:

In [42]:
np.random.randint(1,20,(3,3,3))

array([[[ 9, 10,  3],
        [ 3,  9,  3],
        [ 4,  6, 12]],

       [[12, 10,  4],
        [ 7, 19, 18],
        [16, 16,  3]],

       [[12,  2, 12],
        [16, 19, 17],
        [10,  3,  3]]])

#### 10. Create a 10x10 array with random values and find the minimum and maximum values 

#### Ստեղծեք պատահական թվերով լցված (10x10) չափանի numpy array ու տպեք դրա փոքրագույն ու մեծագույն արժեքները:

In [47]:
np.random.seed(100)
a=np.random.rand(100).reshape(10,-1)
print("max:",np.max(a))
print("min:",np.min(a))

max: 0.9921580365105283
min: 0.004718856190972565


#### 11. Create a random vector of size 30 and find the mean value 

#### Ստեղծեք 30 չափանի պատահական թվերով լցված numpy array ու տպեք դրա միջին արժեքը:

In [53]:
np.random.seed(30)
a=np.random.rand(30)
print(a.mean())
print(np.mean(a))

0.4919474657842404
0.4919474657842404


#### 12. Given a 1D array ranging from 0 to 10, print all the elements which are between 3 and 8. 

#### Ստեղծեք 0-ից 10 հաջորդական թվերով numpy array: Տպեք բոլոր արժեքները, որոնք 3-ից 8 միջակայքում են:

In [62]:
a=np.arange(11)
a=a[4:8]
a


array([4, 5, 6, 7])

#### 13. Given a 1D array of 20 random integers from 0 to 10, multiply the values that are less than 5 by 2 and print the resulting array.

#### Ստեղծեք 1-ից 10 պատահական ամբողջ թվերով լցված 20 չափանի numpy array: Բազմապատկեք 5-ից փոքր արժեք ունեցող տարերրը 2-ով ու տպեք արդյունքում ստացված array-ը:

In [73]:
np.random.seed(124)
a=np.random.randint(1,11, size=(20))
print("old array:",a)
b=np.where(a<5)
a[b]*=2
print("new a",a)

old array: [ 2  8  3 10  1  5  5  6  6  7 10  7  1  9 10 10  1  3  3  2]
new a [ 4  8  6 10  2  5  5  6  6  7 10  7  2  9 10 10  2  6  6  4]


#### 14. Given the 1D array [1, 5, 6, 2, -2, 23, 45], find the indices of the array elements that are divisible by 2.

#### Տրված է [1, 5, 6, 2, -2, 23, 45] numpy array-ը, գտեք 2-ի բաժանվող տարրերի կոորդինատները:

In [75]:
a=np.array([1,5,6,2,-2,23,45])
print(a)
b=np.where(a%2==0)
print("2 divisible:",b)

[ 1  5  6  2 -2 23 45]
2 divisible: (array([2, 3, 4], dtype=int64),)


#### 15. Given a 1D array ranging from 0 to 20, print all the elements which are divisible by 3. 

#### Ստեղծեք 1-ից 20 հաջորդական թվերով լցված numpy array, տպեք բոլոր 3-ի բաժանվող տարրերի արժեքները:

In [79]:
a=np.arange(21)
b=np.where(a%3==0)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
(array([ 0,  3,  6,  9, 12, 15, 18], dtype=int64),)


#### 16. Create a 5x5 numpy array with each row values ranging from 0 to 4 

#### Ստեղծեք 5x5 numpy array, որի ամեն տող իրենից ներկայացնում է 0-ից 4 հաջորդական թվեր:

In [93]:
a=np.arange(5)
b=np.repeat(a,5)
b=b.reshape(5,5)
np.rot90(b)



array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 17. Create the following 2x2 numpy array np.array([[0, 1],[2, 3]]). Find the minimum and maximum values in the array.

#### Ստեղծեք 2x2 numpy array np.array([[0, 1],[2, 3]]) : Գտեք array-ի մեծագույն ու փոքրագույն արժեքները։

In [97]:
a=np.array([[0,1],[2,3]])
np.max(a)
np.min(a)

0

#### 18. Create the following 2x2 numpy array np.array([[0, 1],[2, 3]]). Find the minimum and maximum values in each column.

#### Ստեղծեք 2x2 numpy array np.array([[0, 1],[2, 3]]) : Գտեք array-ի սյուների մեծագույն ու փոքրագույն արժեքները։

In [132]:
a=np.array([[0,1],[2,3]])

print(np.amin(a,1))
print(np.amax(a,1))
     




[0 2]
[1 3]


#### 19. Create  numpy array of size 10 filled with integers of your choice. Compute mean, median, standard deviation and variance of the array values. 

#### Ստեղծեք 10 չափանի numpy array, հաշվեք array-ի mean, median, standard deviation և variance։

In [135]:
a=np.arange(10).reshape(2,5)
print(a)
print(np.mean(a))
np.median(a)


[[0 1 2 3 4]
 [5 6 7 8 9]]
4.5


4.5

#### 20. Calculate the weighted average of the following array: np.array([2, 4, 3, 5, 6, 12, 34, 2, 34, 5]). 

#### Հաշվեք տրված array-ի կշռված միջինը՝ np.array([2, 4, 3, 5, 6, 12, 34, 2, 34, 5])։

In [142]:
a=np.array([2,3,4,5,6,12,34,2,34,5])
print(np.average(a))
wts=np.arange(10,20)

np.average(a,weights=wts)


10.7


11.827586206896552

#### 21. Sort the rows of the following numpy array in an increasing order: np.array([[4, 2, 6, 1],[0, 2, 6, 1],[4, 4, 1, 9]]). 

#### Աճման կարգով դասավորեք տրված numpy array-ի տողերը՝ np.array([[4, 2, 6, 1],[0, 2, 6, 1],[4, 4, 1, 9]]):

In [120]:
a=np.array([[4,2,6,1],[0,2,6,1],[4,4,1,9]])
a.sort()
a

array([[1, 2, 4, 6],
       [0, 1, 2, 6],
       [1, 4, 4, 9]])

#### 22. Create the following numpy arrays and calculate the dot product between a and b. 

#### Ստեղծեք հետևյալ numpy array-ները ու հաշվեք a և b array-ների dot product-ը։

$$a = \begin{bmatrix} 3 & 6 & 7 \\ 5 & -3 & 0  \end{bmatrix}$$

$$b = \begin{bmatrix} 1 & 1 \\ 2 & 1 \\ 3 & -3 \end{bmatrix}$$

In [118]:
a=np.array([[3,6,7],[5,-3,0]])
b=np.array([[1,1],[2,1],[3,-3]])
np.dot(a,b)

array([[ 36, -12],
       [ -1,   2]])